name: Daily Tweet

on:
  schedule:
    - cron: '0 13 * * *'  # 8:00 AM EST (15:30 UTC)
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    timeout-minutes: 10  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # ✅ Downgrade to Python 3.10

    - name: Create log directory
      run: mkdir -p logs

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 2>&1 | tee -a logs/install.log
        pip install -r requirements.txt 2>&1 | tee -a logs/install.log

    - name: Run tweet script
      env:
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      run: python post_tweet.py 2>&1 | tee -a logs/tweet.log

    - name: Log success
      if: success()
      run: echo "Workflow ran successfully on $(date)" >> logs/success.log

    - name: Log failure
      if: failure()
      run: echo "Workflow failed on $(date)" >> logs/failure.log

defaults:
  run:
    shell: bash
    working-directory: .
