name: Daily Tweet

on:
  schedule:
    - cron: '0 14 * * *'  # 9:00 AM EST (15:30 UTC)
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    timeout-minutes: 10  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # ✅ Ensures compatibility

    - name: Create log directory
      run: mkdir -p logs

    - name: Install dependencies
      run: |
        python3 -m pip3 install --upgrade pip setuptools wheel | tee -a logs/install.log
        pip3 install --no-cache-dir -r requirements.txt | tee -a logs/install.log
        pip3 install --no-cache-dir tweepy | tee -a logs/install.log  # ✅ Force-install tweepy separately

    - name: Check Installed Packages
      run: | 
        pip3 list | tee -a logs/install.log

    - name: Run tweet script
      env:
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      run: python3 post_tweet.py | tee -a logs/tweet.log

    - name: Print logs for debugging
      if: always()
      run: cat logs/*.log || true  # ✅ Prints logs to GitHub Actions UI

    - name: Log success
      if: success()
      run: echo "Workflow ran successfully on $(date)" >> logs/success.log

    - name: Log failure
      if: failure()
      run: echo "Workflow failed on $(date)" >> logs/failure.log